app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@AppBundle/Controller/Api/"
    defaults: {"_format": json}
    type:     annotation
    prefix:   /api

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

